global:
    iterations: 1
    batch_size: 5
    batch_randomisation: True
    network: 'fullyconnected_subnetwork_gudi_2015'
    ignore_empty_labels: True
    cost_function: 'cross_entropy'
    threshold: 0.5
    image_size: 48
data:
    dataset: disfa
    number_of_subjects: 3
    train_prop : 1
    valid_prop : 1
    test_prop : 1
