global:
    dump_frames: True
    path: data
    iterations: 1800
    ignore_empty_labels: True
    batch_size: 1000
    batch_randomisation: True
    network: convolution_gudi_2015
    # networks
    #  'fullyconnected_subnetwork_gudi_2015'
    #  'convolution_gudi_2015'
    # lmsq or cross_entropy
    cost_function: cross_entropy
    threshold: 0.5
    dropout_rate: 0.05
    # adam or grad
    optimizer: adam
    # Warning grad needs higher learning rates than adam (100x)
    learning_rate: 0.001
convolutions:
    bias_start: 0.1
    weights_start_type: std_dev # (range,constant,std_dev)
    weights_constant: 0.0
    weights_uniform_range : [-0.5,0.5]
    weights_std_dev: 0.2
data:
    remove_empty_labels: True
    # disfa or mnist
    dataset: disfa
    # -1 Means all the subjects
    number_of_subjects: -1
    # Sizes of each set relative to each other
    train_prop : 5
    valid_prop : 2
    test_prop : 5
    random_batches : True
    # left,right,top,bottom
    crop: [0.1,0.1,0.5,0.2]
    resize_scale: 0.6
    # Defaults:
    # crop: [0,0,0,0]
    # resize_scale: 1.0
